image: maven:3.8.4

pipelines:
  default:
    - step:
        name: Build and Deploy
        script:
          # Build your Spring Boot application using Maven
          - mvn clean install

          # Specify AWS credentials and region
          - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION

          # Deploy using AWS CodeDeploy
          - pipe: atlassian/aws-code-deploy:1.4.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              APPLICATION_NAME: 'unidy_main_server_dev'
              COMMAND: 'upload'
              S3_BUCKET: 'unidy'
              VERSION_LABEL: 'v$BITBUCKET_COMMIT' # Use the commit hash as the version label
              BUNDLE_TYPE: 'zip'
              ZIP_FILE: 'target/your-application.jar' # Adjust the path accordingly
              FILE_EXISTS_BEHAVIOR: 'OVERWRITE' # Adjust based on your requirements
              WAIT: 'true' # Wait for deployment to complete
              WAIT_INTERVAL: '15' # Adjust the interval based on your requirements
              DEBUG: 'true'
