image: maven:3.8.4

pipelines:
  default:
    - step:
        name: Build and Deploy to Dev
        deployment: Develop
        script:
          - echo "Building the Spring Boot project"
          - mvn clean package

          # enable pem file
          - chmod 600 ./$SSH_PRIVATE_KEY

          # Replace 'YOUR-EC2-IP' and 'PATH-TO-PRIVATE-KEY' with your EC2 IP and private key file path.
          - scp -i $SSH_PRIVATE_KEY target/*.jar ubuntur@ec2-13-229-226-68.ap-southeast-1.compute.amazonaws.com:/home/ubuntu/

          - echo "SSHing into EC2 and running the JAR file"
          - ssh -i $SSH_PRIVATE_KEY ubuntu@ec2-13-229-226-68.ap-southeast-1.compute.amazonaws.com "nohup java -jar /home/ubuntu/*.jar > /dev/null 2>&1 &"
