image: maven:3.8.4

pipelines:
  default:
    - step:
        name: Build and Deploy to Dev
        deployment: Develop
        script:
          - echo "Building the Spring Boot project"
          - mvn clean package

          # enable pem file
          - chmod 600 ./$SSH_PRIVATE_KEY

          # upload jar file to ec2
          - scp -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY target/*.jar ubuntur@13.229.226.68:/home/ubuntu/

          - echo "SSHing into EC2 and running the JAR file"
          - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY ubuntu@13.229.226.68 "nohup java -jar /home/ubuntu/*.jar > /dev/null 2>&1 &"
