image: maven:3.8.4

pipelines:
  default:
    - step:
        name: Build and Deploy to Dev
        deployment: Develop
        script:
          - chmod 600 ./unidy_main_server_dev.pem
          - ssh -i  ubuntu@ec2-13-229-237-10.ap-southeast-1.compute.amazonaws.com
          #- scp -o StrictHostKeyChecking=no .env ubuntur@13.229.237.10:/home/ubuntu/
        
          #- echo "Building the Spring Boot project"
          #- mvn clean package

          # upload jar file to ec2
          #- scp -o StrictHostKeyChecking=no target/*.jar ubuntur@13.229.237.10:/home/ubuntu/

          # upload env file to ec2
          #- scp -o StrictHostKeyChecking=no .env ubuntur@13.229.237.10:/home/ubuntu/

          #- echo "SSHing into EC2 and running the JAR file"
          #- ssh -o StrictHostKeyChecking=no ubuntu@13.229.237.10 "nohup java -jar /home/ubuntu/*.jar > /dev/null 2>&1 &"
