image: maven:3.8.4

pipelines:
  default:
    - step:
        name: Build and Deploy to Dev
        deployment: Develop
        script:
          - echo "Building the Spring Boot project"
          - mvn clean package

          # Replace 'YOUR-EC2-IP' and 'PATH-TO-PRIVATE-KEY' with your EC2 IP and private key file path.
          - scp -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no target/*.jar ubuntur@$EC2_IP:/home/ubuntu/

          - echo "SSHing into EC2 and running the JAR file"
          - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no ubuntu@$EC2_IP "nohup java -jar /home/ubuntu/*.jar > /dev/null 2>&1 &"
