image: maven:3.8.4

pipelines:
  branches:
    master:
      - step:
          name: Build and Deploy to Dev
          deployment: Develop
          script:
            - chmod 600 ./unidy_main_server_dev.pem

            # - echo "Building the Spring Boot project"
            # - mvn clean package

            #- echo "upload jar file to ec2"
            #- scp -i ./unidy_main_server_dev.pem -o StrictHostKeyChecking=no target/*.jar ubuntu@ec2-13-212-52-184.ap-southeast-1.compute.amazonaws.com:/home/ubuntu/

            #- echo "upload env file to ec2"
            #- scp -i ./unidy_main_server_dev.pem -o StrictHostKeyChecking=no .env ubuntu@ec2-13-212-52-184.ap-southeast-1.compute.amazonaws.com:/home/ubuntu/

            - echo "SSHing into EC2 and running the JAR file"
            - ssh -i ./unidy_main_server_dev.pem -o StrictHostKeyChecking=no ubuntu@ec2-13-212-52-184.ap-southeast-1.compute.amazonaws.com " curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash && source ~/.bashrc && nvm install v20.11.0 && npm --version && npm install pm2 -g"
            - ssh -i ./unidy_main_server_dev.pem -o StrictHostKeyChecking=no ubuntu@ec2-13-212-52-184.ap-southeast-1.compute.amazonaws.com "pm2 --version"
