services:
  db:
    image: 'mysql:latest'
    volumes:
      - ./data:/docker-entrypoint-initrd.d/:ro
    environment:
      - 'MYSQL_DATABASE=unidy_database'
      - 'MYSQL_PASSWORD=dev'
      - 'MYSQL_ROOT_PASSWORD=dev'
      - 'MYSQL_USER=dev'
    ports:
      - '3306:3306'
    restart: unless-stopped

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    networks:
#      - postgres
#    restart: unless-stopped






