spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${MYSQL_DEV_URI}
    username: ${MYSQL_DEV_USERNAME}
    password: ${MYSQL_DEV_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  neo4j:
    uri: ${NEO4J_DEV_URI}
    authentication:
      username: ${NEO4J_DEV_USERNAME}
      password: ${NEO4J_DEV_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: unidyteam@gmail.com
    password: qmax kecv fcul cfuw

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/certificate/templates/
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days


aws:
  region: "ap-southeast-1"
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}


