spring:
  datasource:
      url: jdbc:mysql://localhost:3306/unidy_database
      username: dev
      password: dev
      driver-class-name: com.mysql.cj.jdbc.Driver
#  neo4j:
#      uri: neo4j://localhost:7687
#      authentication:
#        username: neo4j
#        password: unidyteam
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: unidyteam@gmail.com
    password: gsne smbm pkhi qgws
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days



